declare global {
    interface Tr {
        [key: string]: string
    }
    interface Company {
        id: number,
        companyName: string,
        totalPalmOil: number,
        hq: string,
        regionHq: string,
        regionOfOper: string,
        topBrands: string,
        sector: string,
        applicSector: string,
        companyTotalScore: number,
        ownSupplyChn: number,
        byondSupChain: number,
        respStatus: boolean,
        commitments: {
            commitDef: string,
            commitCpo: string,
            commitPko: string,
            commitPke: string,
            commitPod: string,
            commitCorp: string,
            commitHr: string,
            commitHrCpo: string,
            commitHrPko: string,
            commitHrPke: string,
            commitHrPod: string,
            commitEntCorp: string,
            commitRspoCpo: string,
            commitLaterDate: string,
            commitTotalScore: number
        },
        purchasing: {
            rspoCert: string,
            purchOver: number,
            sgip: number,
            is: number,
            mb: number,
            bAndG: number,
            uncertified: number,
            cpoVolume: number,
            sgipCpo: number,
            isCpo: number,
            mbCpo: number,
            bAndGCpo: number,
            uncertifiedCpo: number,
            pkoVolume: number,
            sgipPko: number,
            isPko: number,
            mbPko: number,
            bAndGPko: number,
            uncertifiedPko: number,
            podVolume: number,
            sgipPod: number,
            isPod: number,
            mbPod: number,
            bAndGPod: number,
            uncertifiedPod: number,
            pkeVolume: number,
            sgipPke: number,
            isPke: number,
            mbPke: number,
            bAndGPke: number,
            uncertifiedPke: number,
            totalEurope: number,
            cspoEurope: number,
            totalNorthAm: number,
            cspoNorthAm: number,
            totalMalaysia: number,
            cspoMalaysia: number,
            totalIndo: number,
            cspoIndo: number,
            totalChina: number,
            cspoChina: number,
            totalIndia: number,
            cspoIndia: number,
            totalLatAm: number,
            cspoLatAm: number,
            totalAfrica: number,
            cspoAfrica: number,
            totalWorld: number,
            cspoWorld: number,
            entireOps: string,
            purchTotalScore: number,
            purchTotalCalcScore: number
        },
        suppliers: {
            supFree: string,
            supHr: string,
            supMonDcfree: boolean,
            supMonHr: boolean,
            supMill: boolean,
            supPlant: boolean,
            supTotalScore: number
        },
        platforms: {
            rspoMember: boolean,
            poigMemeber: boolean,
            memberPlatforms: boolean,
            platformNames: string,
            platformsTotalScore: number
        },
        onTheGround: {
            haveOnTheGrnd: boolean,
            smallHolders: boolean,
            investForest: boolean,
            investLandScape: boolean,
            investCons: boolean,
            groundTotalScore: number
        }
    }
}

export {}  