import { defineStore } from 'pinia'

export const useCsStore = defineStore('csStore', () => {
    const casestudy = ref(null)
    const casestudies = ref([
        {
            id: 247,
            company: 'beiersdorf',
            approach: {
                intro: "<p>As a global skin care company, Beiersdorf does not purchase palm (kernel) oil directly but uses its derivatives for the production of cosmetic products. We strive to take a leading position on sustainability in the palm oil supply chain and focus our <a href='https://www.beiersdorf.com/sustainability/environment/sustainable-land-use/palm-oil' target='_blank'>Sustainable Palm Roadmap</a> on four main pillars:</p>",
                description: "<ul><li><strong>Sustainable Certification:</strong> 100% of our global palm-based raw materials are RSPO Mass Balance certified since end of 2020.</li><li><strong>Transparency:</strong> We gain transparency in our palm supply chain by tracing back our raw materials to the level of mills and plantations.</li><li><strong>Transformation:</strong> We support smallholder farmers and landscape projects with WWF in Indonesia and Malaysia.</li><li><strong>Collaboration:</strong> We collaborate with peer companies and suppliers in key multi-stakeholder initiatives to drive sustainable transformation in the palm supply chain.</li></ul>",
                closing: "<p>We disclose our progress in our annual <a href='https://www.beiersdorf.com/sustainability/reporting/sustainability-reporting' target='_blank'>sustainability report</a> and <a href='https://rspo.org/de/members/4-0125-10-000-00/' target='_blank'>RSPO ACOP report</a>. We received the “CDP Triple A” score on climate, water and forest, including for our sustainable palm program.</p>"
            },
            roadblocks: "<p>Through sustainable certification, transparency, and industry transformation, we aim to identify and minimize environmental and social risks along the palm supply chain. Our <a href='https://www.beiersdorf.com/sustainability/environment/sustainable-land-use/palm-oil' target='_blank'>“Sustainable Palm Roadmap”</a> and our <a href='https://www.beiersdorf.com/~/media/Beiersdorf/sustainability/environment/sustainable-land-use/palm-oil/downloads/Beiersdorf-sustainable-palm-policy-2021.pdf' target='_blank'>“Sustainable Palm Policy”</a> guide us in our worldwide activities for more sustainable raw material sourcing.</p><p>Main challenges are to:</p><ul><li>Achieve traceability to mills and plantation level in the palm (kernel) oil derivatives supply chain, which involves a wide range of different supply chain players</li><li>Obtain RSPO certification and access to the market for independent smallholder farmers in key sourcing countries</li><li>Monitor and manage risks of No Deforestation, No Peat, No Exploitation (NDPE) in the complex palm derivatives supply chain</li></ul>",
            plan: "<p>Moving forward, we will focus our efforts on three key areas:</p><ul><li><strong>Deforestation-Free Supply Chains:</strong> We aim to source our main renewable materials from sustainable and deforestation-free sources by 2025. We set up a task force to ensure compliance with the EU Deforestation Regulation by the end of 2024.</li><li><strong>Transparency & Risk Monitoring:</strong> We gain transparency in our palm supply chain by tracing back our raw materials to the level of mills and plantations. This helps us to identify priority areas, mills and suppliers for engagement and/or risk mitigation.</li><li><strong>Sustainable Transformation:</strong> We collaborate with non-profit and supply chain partners and support various smallholder projects and RSPO certification of farmers in key sourcing countries. Through active participation in industry associations (RSPO, FONAP, Action for Sustainable Derivatives) we aim to achieve sector transformation towards more sustainable palm production.</li></ul>"
        },
        {
            id: 266,
            company: 'danone',
            approach: {
                intro: "",
                description: "<p>In December 2022, Danone issued its <a href='https://www.danone.com/content/dam/corp/global/danonecom/about-us-impact/policies-and-commitments/en/2022/danone-renew-forest-policy-dec-2022.pdf' target='_blank'>Forest Policy</a>, committing to deliver verified deforestation and conversion free supply chains by 2025, while moving towards a forest positive future. It addresses all forms of deforestation and land conversion following the Accountability Framework initiative (AFi) definitions. Our teams made huge progress; by switching towards RSPO Segregated volumes (88% in 2023, 95% in 2023) but also maintaining a high level of traceability (99,3% of TTP, 99,8% in H1 2023). In 2023, Danone was recognized for the fifth year in a row as global environmental leader with triple 'A' score given by CDP - including A rating for Palm.</p>",
                closing: ""
            },
            roadblocks: "<p>Danone has committed to removing deforestation and conversion from its supply chain by 2025 on key commodities including palm. Achieving these targets will not be easy. Land use is driven by competing needs and interests, with many stakeholders involved, many of whom we do not deal with directly. Going beyond certification is key and collaboration sits at the heart of our approach by further investing within and beyond our supply chain and supporting systemic change by working with others via coalitions such as CGF-Forest positive Coalition and the Sustainable Agriculture Initiative Platform – to drive lasting impact.",
            plan: "<p>Our action plan is structured using the 3 core pillars of our Forest policy:</p><ul><li><strong>Clean Supply chains:</strong> our target is 100% verified and fully traceable palm by 2025. We aim to achieve this by reaching the highest percentage of RSPO segregated palm (alongside 100% of traceability to mill and to plantation).</li><li>We will ensure our roadmap also aligns with regulations such as the EU Deforestation regulation.</li><li><strong>Responsible Suppliers:</strong> we continue to engage with direct suppliers and monitor their progress against deforestation and conversion commitments.</li><li><strong>Regeneration:</strong> we will expand our support for landscape projects which transform the palm sector like we already do by collaborating with the Livelihoods Fund for Family Farming since 2021 with a 10-year project to help 2,500 smallholder palm oil farmers achieve a sustainable transition in Sumatra island. but also by supporting the Siak Pelalawan Landscape Program since 2018. We believe that systemic change can only come through wider shifts in policy and society, where our voice in collaboration with others can drive lasting impact - including within coalitions such as CGF-Forest positive Coalition and the SAI Platform.</li></ul>"
        },
        {
            id: 279,
            company: 'ferrero',
            approach: {
                intro: "",
                description: "<p>Ferrero is committed to sourcing palm oil that is 100% RSPO certified segregated and traceable back to plantations, guided by an ambition to transform the industry to benefit people and the planet.</p><p>For Ferrero, this means working with trusted suppliers to improve practices and implement innovative solutions from the ground up. For example, using Starling satellite technology to monitor deforestation over 1.3 million hectares, covering 99.7% of the land we source from. In 2013, we launched our industry-leading Palm Oil Charter which, alongside our Supplier Code, helps track progress, increase transparency, and tackle deforestation and social issues across our supply chain.</p>",
                closing: ""
            },
            roadblocks: "<p>There are many complex issues facing the palm oil industry, from the impact on ecosystems, people and livelihoods, to a lack of awareness around Sustainable Palm Oil (SPO).  At Ferrero, we are focused on tackling these issues throughout our supply chain. For example, preventing deforestation and increasing traceability using Starling satellite technology, and researching and promoting regenerative farming practices.  We are also helping strengthen human rights due diligence through our work with Earthworm Foundation in Malaysia and Guatemala and on-the-ground supplier engagement. Beyond this, we are driving SPO awareness globally via research, consumer education, and partnerships with organisations like Chester Zoo (UK).</p>",
            plan: "<ul><li>Our focus is on increasing sustainability throughout our supply chain, including advancing our Labour Transformation Program with a focus on ethical recruitment and improved working conditions.</li><li>Collaboration is another key focus, particularly helping smallholders achieve certification and compliance with upcoming legislation.</li><li>Assessing and reducing our carbon footprint is a priority, as well tackling deforestation via satellite monitoring and scaling up our ‘Nature-Based Solutions’ project to support regenerative agriculture.</li><ul><li>We remain committed to sourcing 100% RSPO-certified segregated palm oil – traceable back to plantations – for our historical brands, and to continuing to work with our acquired brands to increase traceability and ensure progress on complex issues in line with our commitments.</li></ul>"
        },
        {
            id: 288,
            company: 'bimbo',
            approach: {
                intro: "",
                description: "<p>Grupo Bimbo (GB) has a multi-faceted approach to achieving deforestation and conversion-free (DCF) palm oil by 2025. Our strategy involves fostering industry collaboration, emphasizing the importance of companies working pre-competitively to define and employ a unified approach to tackle larger-scale deforestation. GB is a member of the Consumer Goods Forum (CGF) Forest Positive initiative of more than 20 companies on a mission to remove deforestation, forest degradation, and conversion from key commodity supply chains. GB also works on increasing traceability, increased engagement with key palm oil suppliers, and satellite monitoring of the supply chain to increase our level of DCF supply. Through these approaches, we have successfully verified 60% of our palm oil as DCF. Lastly, to cover our remaining needs, we have obtained 100% RSPO certification as of 2024, with at least Book and Claim certificates for our 2023 volumes.</p>",
                closing: ""
            },
            roadblocks: "<p>Based on the DCF methodology, the key roadblocks to achieving a full DCF supply chain include insufficient traceability, particularly in certain regions, and challenges related to the cost and availability of RSPO segregated volumes. Collaborative efforts with our key suppliers who share our DCF objectives will be instrumental in enhancing traceability across the supply chain. By working with our suppliers, we aim to monitor and achieve our shared goals for a sustainable and deforestation-free supply chain.</p>",
            plan: "<ul><li>At GB, sustainability is not a siloed topic, it’s embedded into the procurement process. We continue to train our Procurement teams on the DCF methodology, incorporating these guidelines into our supplier engagements.</li><li> Further, we will continue to increase our level of traceability, as we work to reach 100% DCF in direct palm oil by 2025 and start to prioritise palm oil derivatives.</li><li> Beyond our supply chain, we will continue to invest in landscape transformation projects in the key regions that we source.</li></ul>"
        },
        {
            id: 302,
            company: 'loreal',
            approach: {
                intro: "",
                description: "<p>In 2021, L’Oréal has reaffirmed the Group’s commitment to forest conservation and rehabilitation, as well as respect to Human Rights, through the publication of its 2030 Forest Policy . For the last 10 years L’Oréal has been actively engaged in a deep transparency work with suppliers towards a sustainable and responsible sourcing of palm.  In 2023, more than 99% of the palm derivatives L’Oréal sources are Roundtable on Sustainable Palm Oil (RSPO) physically certified, with more than 30% of these volumes coming from field projects that support independent smallholders in the adoption of more sustainable practices . In 2023, 90% of L’Oréal’s palm derivatives suppliers were compliant with its policy based on the Sustainable Palm Index (SPI).</p>",
                closing: ""
            },
            roadblocks: "<p>Given the specificity of the palm derivatives market, L’Oréal faces challenges in tracing derivatives back to mills and plantations. Since 2014, L’Oréal has pioneered an innovative approach, tracing 98% of volumes back to refineries, 96% to mills, and 66% to plantations by 2022. Furthermore, due to supply chain fragmentation, some suppliers struggle to adopt sustainable practices. Since 2016, L’Oréal's Sustainable Palm Index (SPI) assesses suppliers' practices, fostering sustainable palm value chains. Additionally, as a founding member of the Action for Sustainable Derivatives (ASD) since 2019, L’Oréal collaborates with over 30 industry leaders to drive collective solutions and market engagement along the supply chain.</p>",
            plan: "<ul><li>L’Oréal remains steadfast in its Forest Policy commitments, striving for 100% traceable, sustainably sourced, and deforestation-free biobased materials.</li><li> Within our palm roadmap, we aim for 100% supplier compliance with our Forest Policy.</li><li> We're dedicated to supporting independent smallholders and engaging stakeholders within coalitions of action.</li><li> Our priorities include upholding human rights, promoting regenerative agriculture, and preserving climate and biodiversity.</li><li> Through collective efforts, we're driving sector-level change and addressing common challenges head-on.</li></ul>"
        },
        {
            id: 304,
            company: 'lg',
            approach: {
                intro: "",
                description: "<p>Palm oil serves a vital role in cosmetics and household products, from direct raw materials like fatty acids to processed ingredients like glycerin. LG H&H acknowledges the grave issues of human rights violations and environmental harm linked to palm oil production. In response, we endorse and actively participate in the RSPO, a global initiative engaging NGOs and companies. Our Ulsan and Onsan facilities obtained RSPO Segregation certification in 2014, ensuring sustainability across the entire production process. We renewed this certification in 2019 and remain vigilant, instantly terminating any deals with supply chains associated with human rights violations in palm oil production. Our commitment to sustainable palm oil is embedded in our sustainable purchasing policies, reflecting our dedication to responsible sourcing and environmental stewardship.</p>",
                closing: ""
            },
            roadblocks: "<p>As the number of overseas operations that procure raw materials from around the world increases and are in charge of greater production and distribution in the market, the scope of human rights and environmental obligations and responsibilities for companies is expanding, and investors and stakeholders' demands for supply chain management are further expected to increase. We are expanding our certification of sustainable palm oil to prevent human rights violations and environmental destruction that may occur in procuring raw materials. In addition, we are developing a sustainable supply chain process by evaluating major suppliers in human rights and the environment sectors.</p>",
            plan: "<ul><li>LG H&H is trying to expand the ratio of our annual RSPO-certified sustainable palm oil purchases from 61.5% in 2022, to 70% in 2025.</li><li> Most of the current RSPO purchase is through book & claim method, but in the future, LG H&H plans to purchase MB/SG grade palm oil to increase impact.</li></ul>"
        },
        {
            id: 305,
            company: 'lidl',
            approach: {
                intro: "",
                description: "<p>The Lidl strategy for sustainable palm oil supply chains focuses on increasing the supply chain transparency but also the implementation of sustainable certification standards within our products. Therefore, Lidl conducts yearly supplier mapping and interviews, to gain transparency about the origin and certification status of the palm (kernel) oil used for Lidl products and to report about this. Furthermore, Lidl has been collaborating with different stakeholders in the palm oil sector such as FONAP & RSPO for several years. Regarding the implementation of sustainable standards, Lidl assures that 100% of our products containing palm (kernel) oil and palm (kernel)- based derivatives/fractions have been RSPO-certified via the segregated and Mass Balance approach since 2022.</p>",
                closing: ""
            },
            roadblocks: "<p>Lidl considers solid certification standards as an important baseline regarding the sustainable production of palm oil-based products. Therefore, Lidl supports initiatives in continuously improving standards and certifications in cooperation with organisations such as the RSPO, ISSC, Rainforest Alliance, FONAP. Herewith we aim to improve e.g. environmental and human conditions, biodiversity and monitoring mechanisms on oil palm plantations.</p>",
            plan: "<ul><li>Lidl is focused on further increasing the transparency of its palm oil supply chains and extending sustainable standards to our whole product line.</li><li> Another important part of the Lidl strategy will be to continue and deepen our cooperation with different stakeholders. Together we will work on diverse sustainability solutions to meet the necessary requirements for palm oil-based products , such as through smallholder projects (e.g. with FONAP).</li><li> With respect to the EUDR, Lidl wants to continue improving traceability within the palm oil supply chains and ensure deforestation and conversion-free palm oil-based products.</li></ul>"
        },
        {
            id: 307,
            company: 'lotte-wedel',
            approach: {
                intro: "",
                description: "<p>Wedel started the transition to sustainable palm oil in 2019, then, as the entire LOTTE group, we joined the organisation on its journey to sustainable palm oil and RSPO. Since then, we have made significant progress in purchasing sustainable palm oil. In December 2020 we passed the Mass Balance standard certification audit , and we currently buy 100% certified palm oil in two models: MB and SG. The process of switching and replacing raw materials with certified palm oil took about a year. Responsible sourcing of raw materials from certified sources is part of our ESG (environment, social, governance) strategy. One of the significant initiatives in which the company participates to this day is being one of  founding members of the Polish Coalition for Sustainable Palm Oil (PKZOP).</p>",
                closing: ""
            },
            roadblocks: "<p>Navigating the certification process for raw materials containing palm oil derivatives remains a significant market challenge. To address this, we made the bold decision to eliminate uncertified additives containing palm oil derivatives, despite the difficulty posed by their uniqueness as raw materials. Implementing rigorous procedures, we now verify palm oil presence and RSPO certification at the outset of the raw material search process. Additionally, we've undertaken the challenge of assessing our palm oil suppliers for their awareness and responsible business practices. Recognising the disparity in supplier actions towards responsible palm oil sourcing, we conduct regular surveys to gauge progress and encourage responsible decision-making in raw material sourcing. Through these proactive measures, we're committed to upholding sustainable practices and driving positive change in the industry.</p>",
            plan: "<ul><li>In the upcoming years, our primary focus will be on sustaining our commitment to purchasing 100% certified palm oil through the SG model, while actively seeking opportunities to further increase our procurement of palm oil under this sustainable model.</li><li>In collaboration with the Polish PKZOP Coalition, we will intensify efforts to raise consumer awareness regarding certified palm oil, enhance employee education, and promote RSPO standards among consumers.</li><li> Aligned with the new EUDR regulation, we will prioritize collaboration with suppliers to implement policies and initiatives aimed at combating deforestation associated with palm oil production. This proactive approach underscores our dedication to responsible sourcing and environmental preservation.</li></ul>"
        },
        {
            id: 318,
            company: 'nutreco',
            approach: {
                intro: "",
                description: "<p>Nutreco is committed to achieving a deforestation-free supply chain by the end of 2025. To realize this goal, we've implemented a sourcing policy specifically targeting soy and oil palm ingredients. This policy assesses the risk of deforestation based on the country of cultivation and the use of appropriate certification. Notably, our efforts have shown significant progress; in 2020, 53% of our palm purchases had a low deforestation risk, a figure that increased to 66% by 2022.</p>",
                closing: ""
            },
            roadblocks: "<p>One of the significant challenges we faced was the difficulty in determining whether purchased palm oil posed a low risk of deforestation. To address this, we developed a clear sourcing policy with a decision tree to guide our procurement department in making informed decisions.Furthermore, we've observed an increasing emphasis on carbon footprint and other life cycle assessment (LCA) metrics for identifying sustainable ingredients. Notably, deforestation-free palm oil often exhibits lower carbon footprints due to reduced land use change. However, there's currently no established alignment between certifications and chain of custody models that directly correlate with emission reductions that Nutreco is aware of. Addressing this gap is essential for the entire industry to ensure sustainable practices.</p>",
            plan: "<p>We are actively pursuing RSPO certification for a portion of our business to provide RSPO certified products to customers in targeted markets. Concurrently, we continue to advocate for the use of RSPO credits throughout our operations. By 2026, our aim is for the vast majority, if not all, of our palm purchases to be sourced sustainably. This commitment underscores our dedication to promoting sustainable palm oil practices and meeting the evolving demands of our customers and markets.</p>"
        },
        {
            id: 320,
            company: 'p&g',
            approach: {
                intro: "",
                description: "<p>P&G recognizes benefits of palm oil (land-efficiency/versatility) but, unless managed sustainably, there can be environmental and social concerns. In 2023 we published our renewed P&G Forest-Commodities-Policy (including NDPE expectations). Our work focuses on 3 pillars:<p><ul><li>Sourcing Fundamentals – supply chain traceability (98% to Mill); transparency (public mill/ supplier lists) and achieving 100% RSPO preference for our brands.</li><li>Compliance Monitoring – satellite monitoring enables continual compliance assurance and when needed rapid, robust investigation and stakeholder engagement.</li><li>Partnering - Force-for-Good – engaging in sector wide solution forums (e.g. RSPO, POCG, HCSA) and partnering on nature and social programs e.g. WWF, RIMBA Collective.</li></ul> <p>Learn More: P&G ESG-Palm-Oil</li></p>",
                closing: ""
            },
            roadblocks: "<p>Our challenges are ones shared across the sector, but especially by purchasers of palm kernel oils. Demand for palm kernel oil continues to grow but the pace is not matched by growth in RSPO certified production volumes. Traceability is a growing focus (enabling governance and stakeholder engagement) but going beyond palm oil mills to farms presents a unique challenge, especially for more complex PKO supply chains. It will require identification of shared industry solutions. Smallholder sustainability and inclusion needs on-going focus, with solutions enabled by participation and access to sustainable best practice and technology, delivering positively for people and the planet.</p>",
            plan: "<ul><li>Partnership – shared challenges, need shared solutions. We will continue our work with industry (e.g. POCG, HCSA), and expert (e.g. RSPO, WWF) organisations.</li><li> Jurisdictional Scale – development of a pilot JA in Johor Malaysia (with WWF and RSPO) to scale availability of sustainable oils, establish consistent due diligence and shared accountability for best-practices across multi-stakeholder communities.</li><li> Smallholders – continue expanding our program, for inclusion that lifts up communities and protects nature, through access to best agricultural practice solutions, RSPO RISS certification etc.</li><li> Force-for-Good – supporting partnership programs that seek to achieve better outcomes for communities and nature e.g. RIMBA Collective, WWF Malaysia Tiger.</li></ul>"
        },
        {
            id: 328,
            company: 'sainsburys',
            approach: {
                intro: "",
                description: "<p>Sainsbury’s is committed to eliminating deforestation and conversion from our palm oil supply chains. We seek to achieve this by ensuring all palm oil in our food and non-food own brand products is RSPO certified. Since 2021, 100% of the palm oil in our products has been physically certified with around 82% and 18% of Segregated and Mass Balance volumes. To solve the remaining challenges in palm oil supply chains, we work with other businesses through the UK Sustainable Palm Oil Initiative, the Palm Oil Transparency Coalition, the Retail Palm Oil Group and the Forest Positive Coalition.</p>",
                closing: ""
            },
            roadblocks: "<p>Sainsbury’s has a relatively small palm oil footprint compared to the global demand for palm oil. To improve traceability in supply chains we therefore need to collaborate with other businesses, including retailers. This is an approach we are pursuing with oleochemicals where we want to improve traceability so we can source Segregated palm oil where we currently use the Mass Balance approach. We also realise it is challenging for smallholders to meet the traceability requirements of UK businesses and legislation. Since 2022, we have invested £300,000 in a landscape initiative in Sintang, Indonesia, which aims to support smallholders and help them achieve RSPO certification.</p>",
            plan: "<ul><li>While we continue to act as a leading member of the Palm Oil Transparency Coalition, we are working through the UK Oleochemicals Working Group to pursue greater traceability in oleochemical supply chains and signal market demand for oleochemicals that use sustainable palm oil.</li><li> We also plan to examine how palm oil and palm kernel expeller used in animal feed can be sourced more sustainably, with a focus on dairy supply chains.</li><li> This will sit alongside our existing work which includes support for the landscape initiative in Sintang as it works with the local government to protect endangered forests and support farmers with certification.</li></ul>"
        },
        {
            id: 346,
            company: 'unilever',
            approach: {
                intro: "",
                description: "<p>At Unilever, we have been working to deliver a sustainable deforestation-free supply chain, especially for the raw materials with the highest environmental and social risks, such as palm oil. By the end of 2023, we achieved a remarkable 97% deforestation-free score for our direct palm oil supply chain, independently verified. We're a leading buyer of certified palm oil and smallholder credits, supporting responsible production. With over 25,000 smallholders mapped, our inclusive approach fosters sustainable livelihoods and environmental stewardship. Moving forward, we'll continue to drive innovation and collaborate for a more sustainable future.</p>",
                closing: ""
            },
            roadblocks: "<p>Our progress in achieving sustainable and deforestation-free palm oil highlights the challenges, particularly in securing enough sustainable palm kernel oil. To enact meaningful change, we've moved beyond relying solely on limited certified sources. Instead, we're engaging with independent mills and smallholders, often overlooked in certified supply chains. By directly purchasing from mills, we drive demand for sustainable production, incentivising smallholders and mills to adopt higher standards. This approach fosters inclusive supply chains, ensuring that smallholders aren't marginalised in an ever-changing industry landscape.</p>",
            plan: "<p>Unilever remains steadfast in our commitment to sustainability, collaborating with partners and industry peers to implement our People and Nature Policy for a sustainable palm oil supply chain.</p><ul><li>We will continue to invest in our infrastructure to sustain and strengthen the impact of our deforestation free supply chain.</li><li> We will leverage technology partnerships to drive exponential progress in traceability and transparency.</li><li>We will seek to strengthen and expand our impact on sustainable livelihoods through our investment in smallholder development hubs working with 40,000 smallholder farmers.</li><li> Advancing change beyond our own supply chain with our strategy to invest in landscape and jurisdictional approaches that seek to protect and restore natural ecosystems, drive responsible production at scale and empower whole communities.</li><li>Invest in product innovation and reformulation to ensure growth with diversified and sustainable feedstocks and manage a just transition to net zero.</li></ul>"
        },
        {
            id: 276,
            company: 'edeka',
            approach: {
                intro: "",
                description: "<p>Palm oil is a focus area in the partnership between EDEKA and WWF Germany. The main activities are:<p><li>Use of certified palm oil components according to the Round Table on Sustainable Palm Oil (RSPO) and improvement of the standard: in the meantime 100 % of the used palmoil components are RSPO certified.<ul><li> Ensuring the use of sustainable palm oil substitutes through definition of requirements for sustainable production for rapeseed, sunflower, soy etc.</li><li> Engagement for a holistic transformation of the palm oil industry within the framework of pre-competitive cooperation such as in the Forum nachhaltiges Palmöl e.V. (FONAP).</li><li> Ensuring supply chains free from deforestation and conversion</li></ul>",
                closing: ""
            },
            roadblocks: "<p>EDEKA is strongly committed to reduce its environmental footprint. For this purpose a sustainable conception, sourcing and production of EDEKA’s private label assortment are key elements. To design a sustainable palm oil sourcing, our activities focus on:<p><li>Ensuring deforestation and conversion free supply chains for EDEKA’s private label products according to the specifications of the Accountability Framework Initiative (AFi) until 2025.</p><ul><li> Mapping of the palm oil supply chain and analysis of EDEKA’s real deforestation and conversion risk.</li><li> Systematic collection of supply chain data as well as monitoring of supplier performance.</li><li>Public reporting of progress</li></ul>",
            plan: "<p>In the future, the partnership between EDEKA and WWF will focus even more on achieving the greatest possible impact within the company, along supply chains and in procurement processes. In doing so, EDEKA will concentrate on systematically recording and analyzing risks in the private label assortment and developing tailor-made measures with scaling potential to reduce risks. Especially for palm oil EDEKA will focus on creating transparency and achieve a high level of traceability. Beyond EDEKA’s own supply chain, we promote transformation of the entire value chain by supporting especially low performing suppliers with the implementation of ethical and environmental supply chains.</p>"
        },
        {
            id: 284,
            company: 'godrej',
            approach: {
                intro: "",
                description: "<p>Godrej Industries Limited Chemicals is a leading manufacturer of Oleo chemicals, essential for industries like personal care and pharmaceuticals. Committed to sustainability, we've joined ASD and RSPO, offering certified RSPO Mass Balance products. Both our facilities are RSPO certified. In 2022, we achieved 100% traceability to refineries, 93.8% to mills, and 65.5% to plantations, addressing the challenge of transparency in palm oil supply chains.</p>",
                closing: ""
            },
            roadblocks: "<p>To address challenges in sustainable palm oil sourcing, Godrej has instituted a 'Sustainable Palm Oil Policy', aiming to impact production positively. Through this, we engage suppliers, enhance transparency via ASD, and drive traceability. Our dedicated 'Extension Team' collaborates with smallholder farmers, promoting sustainable farm management. We evolve sourcing practices, monitor risks, and uphold ethical standards, fostering an inclusive and resilient supply chain.</p>",
            plan: "<ul><li>Over the next 5 years, Godrej Industries Limited Chemicals plans to achieve 100% transparency up to mills, refineries, and plantations in our palm oil supply chain.</li> <li>We'll drive this change across our supply chain, strengthen sustainable sourcing standards, and increase supplier engagement.</li><li>We aim to boost volumes of sustainable palm oil derivatives while continuing our Smallholder Program to empower farmers with sustainable practices, improving livelihoods.</li></ul>"
        }
    ])

    return {
        casestudy,
        casestudies
    }
})